<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="ETP-QATEST10" name="DriverScript.JDA" tests="4" failures="0" timestamp="16 Jan 2020 06:59:16 GMT" time="28.880" errors="1">
  <testcase name="JDASupersession" time="0.000" classname="DriverScript.JDA">
    <skipped/>
  </testcase> <!-- JDASupersession -->
  <testcase name="beforeTest" time="28.880" classname="DriverScript.JDA">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at il.co.topq.difido.reporters.AbstractDifidoReporter.log(AbstractDifidoReporter.java:412)
at il.co.topq.difido.reporters.AbstractDifidoReporter.log(AbstractDifidoReporter.java:432)
at il.co.topq.difido.ReportManager.log(ReportManager.java:74)
at il.co.topq.difido.ReportManager.log(ReportManager.java:85)
at DriverScript.JDA.beforeTest(JDA.java:81)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- beforeTest -->
  <testcase name="JDAPIMSupersession" time="0.000" classname="DriverScript.JDA">
    <skipped/>
  </testcase> <!-- JDAPIMSupersession -->
  <testcase name="JDADemandWorkBench" time="0.000" classname="DriverScript.JDA">
    <skipped/>
  </testcase> <!-- JDADemandWorkBench -->
</testsuite> <!-- DriverScript.JDA -->
